### ISSUE TITLE
infer: add --null-as for --graphql

### ISSUE THREAD

**Issue by thomasdfischer** [Confbase/schema#62]

**Comment by thomasdfischer** [comment]
see --empty-arrays-as for an idea of how to complete this

**Comment by theishshah** [comment]
I'm down to take this on. Quick question, are we only going have nil supported types or do we want to fall back on 0/false for primitives?

**Comment by theishshah** [comment]
Opened PR #68

**Comment by thomasdfischer** [comment]
#68 closes this
